version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: mizuki
      POSTGRES_PASSWORD: mizuki
      POSTGRES_DB: mizuki
    restart: always
    networks:
      - practice
networks:
  practice:
